### ISSUE TITLE
release on packagist

### ISSUE THREAD

**Issue by schliflo** [wp-cli/wp-super-cache-cli#27]
## Feature Request

 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Currently this package is not installable via packagist like many other packages are: https://packagist.org/?query=wp-cli%2F

**Describe the solution you'd like**

Release this on packagist

**Comment by schlessera** [comment]
Thanks for the request, @schliflo !

Here you go: https://packagist.org/packages/wp-cli/wp-super-cache-cli

**Comment by schliflo** [comment]
thank you @schlessera 👍
