### ISSUE TITLE
--post_id gets disrespected

### ISSUE THREAD

**Issue by mondalaci** [wp-cli/wp-super-cache-cli#8]
When I invoke `wp-cli super-cache flush --post_id=123` the post id gets disrespected. It doesn't matter what I specify, the whole cache gets flushed.

**Comment by danielbachhuber** [comment]
Can you verify `wp_cache_post_change()` is what's being called? See https://github.com/wp-cli/wp-super-cache-cli/blob/master/cli.php#L26

**Comment by mondalaci** [comment]
I can confirm that `wp_cache_post_change()` is being called. But I've also noticed that `wp-cli post update $postId $filePath` updates the page in question with super cache enabled and without explicitly executing a flush. Is this normal? If so, then I probably shouldn't have reported this issue as `update` flushes the cache automatically.

**Comment by danielbachhuber** [comment]
> But I've also noticed that `wp-cli post update $postId $filePath` updates the page in question with super cache enabled and without explicitly executing a flush. Is this normal?

Yes, because WP Super Cache hooks into the `save_post` hook.

**Comment by mondalaci** [comment]
Ah, gothca! Then chances are it's not an issue at all. Thanks!
