### ISSUE TITLE
The index page doesn't get flushed

### ISSUE THREAD

**Issue by mondalaci** [wp-cli/wp-super-cache-cli#9]
`flush` clears the whole cache except our main page which is https://ultimatehackingkeyboard.com

In the settings page the WordPress Address is https://ultimatehackingkeyboard.com/wordpress and the Site Address is https://ultimatehackingkeyboard.com/wordpress

The relevant nginx configuration which might also affect the situation is:

```
    location / {
        # Redirect from the front page to the blog.
        rewrite "^/$" /wordpress/index.php last;

        # Use WordPress search when encountering with any non-existing files.
        if (!-e $request_filename) {
            rewrite ^(.+)$ /wordpress/index.php?q=$1 last;
        }
    }
```

**Comment by danielbachhuber** [comment]
> The relevant nginx configuration which might also affect the situation is:

Given there's no way for WordPress to know of which path it's actually being served at, I think it's outside the scope of the CLI command to magically ensure the cache is appropriately flushed.
